### ISSUE TITLE
Information for this repo 

### ISSUE THREAD

**Issue by mbouazza** [it-projects-llc/saas-addons#105]
Hi all,

I ask you if this ripository is operational, if yes what is the possibility to have an operational version please, currently I am working with your ODOO V10 project odoo-saas-tools

thank you for your time

**Comment by ilmir-k** [comment]
Hi @mbouazza ,

Yes. This is our new version of Odoo SaaS and we continue to develop it.
The current version of the system is available for v12 but we could consider a backport to v10 if needed.

If you would like to get our offer and discuss the details please ping us by email saas@it-projects.info

**Comment by mbouazza** [comment]
Hi @ilmir-k  th ping is done, i wait your pong ^-^
