### ISSUE TITLE
'web_notify' module not found [v12.0]

### ISSUE THREAD

**Issue by herawais** [it-projects-llc/saas-addons#113]
![image](https://user-images.githubusercontent.com/13944805/87663671-a4ec2400-c77d-11ea-9e9c-16ebd5fc73f2.png)

**Comment by ilmir-k** [comment]
https://github.com/OCA/web/tree/12.0/web_notify

**Comment by herawais** [comment]
> https://github.com/OCA/web/tree/12.0/web_notify

Okay thanks Got it.
