### ISSUE TITLE
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"

### ISSUE THREAD

**Issue by herawais** [it-projects-llc/saas-addons#114]
I tried the [One-server deployment](https://github.com/it-projects-llc/saas-addons/blob/12.0/saas_demo/doc/index.rst#id2) Commands On.
1. Digital ocean Fresh droplet (Ubuntu 18.04) same error
2. Microsoft Azure (Ubutu 18.04) new instance but same error.
![image](https://user-images.githubusercontent.com/13944805/87878396-69f82380-c9fd-11ea-87c6-773eac257285.png)

**Comment by herawais** [comment]
Complete logs are here. After running this command error occours
docker-compose run dodoo init -n apps -m saas_demo --no-demo --no-cache
https://gist.github.com/herawais/94baf968d59f62cbc1134b8975c3b771
But the docker container is running, and i am able to connect it externally.

**Comment by ilmir-k** [comment]
Did you make this?
```
export COMPOSE_IMPERSONATION='0:0'
make info
```

**Comment by herawais** [comment]
> Did you make this?
> 
> ```
> export COMPOSE_IMPERSONATION='0:0'
> make info
> ```

Yes I make this.
I found a solution. I created a new digitalocean droplet again.. Before running any command of Odoo SaaS. I installed **make**, **docker** and **docker compose**
Then it was working fine.
