### ISSUE TITLE
You try to install module 'saas' that depends on module 'web_notify'.

### ISSUE THREAD

**Issue by killday** [it-projects-llc/saas-addons#123]
But the latter module is not available in your system. 

That's on v15, OCA web_notify is not available. How to install it?

**Comment by em230418** [comment]
Hi, @killday!
web_notify is on PR: https://github.com/OCA/web/pull/2176

**Comment by killday** [comment]
Hi @em230418 thank you

**Comment by killday** [comment]
So how can I install SaaS Base on 15.0
