### ISSUE TITLE
[14.0] jobs build_post_init, action_install errors db isn't exist

### ISSUE THREAD

**Issue by gaelTorrecillas** [it-projects-llc/saas-addons#134]
Hello,

We use saas on OCB 14.0 with this configuration on master (is odoo create others odoo): 
workers:            4
max_cron_threads:   3

When we create one db, we have 3 jobs : 
create_db
action_install_missing_mandatory_modules
build_post_init

The job create_db the software runs for a few minutes but the other jobs don't stay and raise error : 
The db is not exist

And when create_db finish, we have the db

do you know how i can fix this problem?

**Comment by killday** [comment]
Hi,

If you do these jobs manually, you should wait the create_db status to become ready (refresh page) and then do the rest.
If you do them by script it will need again to check the status of the job and then start next one which status you will need to check too.

**Comment by gaelTorrecillas** [comment]
Hi,

when we create new db with button on template ( open wizard etc.) all jobs are launch, we can't run one after other.
How you create these jobs manually?

**Comment by killday** [comment]
Hi

the jobs are started in order -> crate database ->Module installation -> Extra initialization
Module installation should not start before Create database
![template_create](https://user-images.githubusercontent.com/6714294/181020308-65954331-ce70-43c5-883a-cb4f6c65453c.PNG)

**Comment by gaelTorrecillas** [comment]
Hello @killday, yes but the db is not created before the launch module installation, so this job will be error status.

I tested the group of job delay this pr : https://github.com/it-projects-llc/saas-addons/pull/139

**Comment by em230418** [comment]
Fixed by https://github.com/it-projects-llc/saas-addons/commit/c858615f8b8e609889eca7aeed741356dfae01a3
