### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by anandsork** [it-projects-llc/saas-addons#136]
Can someone please guide or point to the documentation on how to use this on Odoo 14 or 15?
The video link (http://runbot.it-projects.info/demo/saas-addons/14.0  under SaaS directory) does not work.

What I have done:
I have installed (locally on windows) odoo 14 (& also tried with 15). Then added all the modules by enabling the developer mode. the dependent modules are also downloaded & added.
However now I do not know how to create plan, saas user and its associated db. I saw some templates, build etc in SaaS tab. I tried to create build, but it is still in draft. 
(Also tried to follow at https://github.com/it-projects-llc/saas-addons/blob/12.0/saas/doc/index.rst, but in vein)
Not sure if I have to do extra things. 

There is some documentation on its predecessor (https://odoo-saas-tools.readthedocs.io/), but not sure if that is still valid.

**Comment by killday** [comment]
There is documentation in each module,
Start from here:
https://github.com/it-projects-llc/saas-addons/blob/14.0/saas/doc/index.rst
https://github.com/OCA/queue/tree/14.0/queue_job#configuration
https://github.com/it-projects-llc/saas-addons/blob/14.0/saas_apps/doc/index.rst
https://github.com/it-projects-llc/saas-addons/blob/14.0/saas_build_admin/doc/index.rst

**Comment by anandsork** [comment]
Closing this.. as I finally figured out how to install.
Thanks @killday
