### ISSUE TITLE
Do not create a database locally

### ISSUE THREAD

**Issue by Salvador1994** [it-projects-llc/saas-addons#36]
I would like to know if the module already allows the creation of a local database, if yes what is the procedure for creating a database locally.

I'm trying to create a local database and I can't,
the database is created in the saas.template.operator model but remains in the creating state, and when I try to build it I get the message "There are no ready template's deployments. Create new one or wait until it's done." as an answer.

I would appreciate your help on how to resolve this error in creating a database locally.

**Comment by trojikman** [comment]
> I would like to know if the module already allows the creation of a local database, if yes what is the procedure for creating a database locally.
> 
> I'm trying to create a local database and I can't,
> the database is created in the saas.template.operator model but remains in the creating state, and when I try to build it I get the message "There are no ready template's deployments. Create new one or wait until it's done." as an answer.
> 
> I would appreciate your help on how to resolve this error in creating a database locally.

1) How many workers do you have? Need at least 2, I usually set the value to 3.
2) Did you restart the odoo as documentation says?

**Comment by Salvador1994** [comment]
Ok. Now i'm setting up odoo with multiple workers. What documentation I should follow to use this module?

**Comment by trojikman** [comment]
> Ok. Now i'm setting up odoo with multiple workers. What documentation I should follow to use this module?

https://github.com/it-projects-llc/saas-addons/blob/12.0/saas/doc/index.rst  and https://github.com/OCA/queue/tree/12.0/queue_job
