### ISSUE TITLE
No information in how to configure auth_quick

### ISSUE THREAD

**Issue by aliencrash** [it-projects-llc/saas-addons#38]
How to configure auth_quick properly?

This info I found, but I don't understand where the parameters should be configured
Create following key-value records:

    auth_quick.master -- url to master server.
    auth_quick.build -- reference for this database
I'm testing this locally,  which database should I put the parameter and who is master and build database.

**Comment by trojikman** [comment]
> How to configure auth_quick properly?
> 
> This info I found, but I don't understand where the parameters should be configured
> Create following key-value records:
> 
> ```
> auth_quick.master -- url to master server.
> auth_quick.build -- reference for this database
> ```
> 
> I'm testing this locally, which database should I put the parameter and who is master and build database.

key-value records should be created in ir.config_parameter model inside build database.
It should be like this:
`env['ir.config_parameter'].create([{'key': 'auth_quick.master', 'value': 'master_url}])`
`env['ir.config_parameter'].create([{'key': 'auth_quick.build', 'value': build_id}])`

What are you using this module for? The code may look specific because it was created for internal use by our saas modules.
You can find out how it works in the saas module.

**Comment by yelizariev** [comment]
The module documentations explains where to set: https://github.com/it-projects-llc/access-addons/blob/12.0/auth_quick/doc/index.rst

> Open menu [[ Settings ]] >> Technical >> Parameters >> System Parameters

**Comment by yelizariev** [comment]
Also, you can check this README about how it works: https://github.com/it-projects-llc/saas-addons/blob/12.0/auth_quick_master/README.rst

**Comment by aliencrash** [comment]
> > How to configure auth_quick properly?
> > This info I found, but I don't understand where the parameters should be configured
> > Create following key-value records:
> > ```
> > auth_quick.master -- url to master server.
> > auth_quick.build -- reference for this database
> > ```
> > 
> > 
> > I'm testing this locally, which database should I put the parameter and who is master and build database.
> 
> key-value records should be created in ir.config_parameter model inside build database.
> It should be like this:
> `env['ir.config_parameter'].create([{'key': 'auth_quick.master', 'value': 'master_url}])`
> `env['ir.config_parameter'].create([{'key': 'auth_quick.build', 'value': build_id}])`
> 
> What are you using this module for? The code may look specific because it was created for internal use by our saas modules.
> You can find out how it works in the saas module.

We are testing in the SaaS module. So in the build wizard this should be passed by default?
