### ISSUE TITLE
Access Template Database

### ISSUE THREAD

**Issue by sariamirza** [it-projects-llc/saas-addons#42]
After creating a template how can I access it? , I access the build instance via entering 'auth_quick.master' and auth_quick.build at creating the build!

**Comment by trojikman** [comment]
> After creating a template how can I access it? , I access the build instance via entering 'auth_quick.master' and auth_quick.build at creating the build!

direct access to the template was not provided

**Comment by sariamirza** [comment]
@trojikman Thanks for answering, so it's not like saas_portal which I can configure the template and then create a build based on that configuration? now the options just install the modules and pass Initialization! is it true?

**Comment by yelizariev** [comment]
@sariamrza we made it impossible to configure manually. You need to put all configuring in the initialization code

**Comment by yelizariev** [comment]
For that reason, we made it impossible to log in to the template database.

**Comment by yelizariev** [comment]
It's because a template can be deployed on different servers and it's not convenient to make manual configuration on all those servers
