### ISSUE TITLE
saas_runbot

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/saas-addons#49]
We plan to implement runbot-like feature via SaaS system. While original [runbot](runbot.odoo.com) makes single build for a specific odoo version, the ``saas_runbot`` will allow to make personal build for each tester.

The full workflow as follows:
* Developer send a Pull-Request to some repository (e.g. https://github.com/it-projects-llc/pos-addons )
* Github shows status check with a link:
![screenshot-github com-2019 09 01-12_06_14](https://user-images.githubusercontent.com/186131/64072968-0368fa80-ccb1-11e9-999a-9d900b3837eb.png)
* The links opens a build information page with the following info:

  * Logs for template database creation
  * Button to make personal build, which opens new page that has:

     * Button "Log in as Admin"
     * Button "Log in as Demo"
     * Build Logs

If are interested to have such Fast Runbot, consider to sponsor the development via bountysource

**Comment by elvise** [comment]
Hi Man!
what's the status of this ?

**Comment by yelizariev** [comment]
I actually canceled this idea and would prefer to implement CI solution based on this tool: https://github.com/itpp-labs/DINAR
