### ISSUE TITLE
Slugify Not Found

### ISSUE THREAD

**Issue by elitesolpro** [it-projects-llc/saas-addons#52]
Greetings,

I came across your solution and I would like to thank you first for this great effort.

I went through the steps to install, but I am getting this error:
 **"Unable to install module "saas" because an external dependency is not met: No module named slugify"** 

However, Slugify is installed:

"Requirement already satisfied: python-slugify in c:\program files (x86)\python37-32\lib\site-packages (from -r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: text-unidecode==1.2 in c:\program files (x86)\python37-32\lib\site-packages (from python-slugify->-r requirements.txt (line 1)) (1.2)

I am using the following parameters for testing:

1. OS: Windows 10 Pro 64 Bit
2. Odoo 12.0-20181022 (Community Edition)

Can you please advise me where I failed? also which is better for implementing Odoo and SaaS, Windows or Ubuntu?

Thanks in advance for your help.

**Comment by elitesolpro** [comment]
Hi,

I found the error. The Slugify was installed in another Python Environment. I have installed it into the same environment and the installation completed.

Thanks

**Comment by nebuashish** [comment]
Can you please explain how to fix that problem in details?
There is no python virtual environment of Odoo on our local machine. Where should we import the slugify to make it work?

**Comment by trojikman** [comment]
> Can you please explain how to fix that problem in details?
> There is no python virtual environment of Odoo on our local machine. Where should we import the slugify to make it work?

Run `pip install python-slugify` in your environment
